name: build and deploy

on: push

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      uses: shalzz/zola-deploy-action@v0.17.1
      env:
        BUILD_ONLY: true

    - name: deploy sftp
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ftp.cluster014.hosting.ovh.net
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        forceUpload: true
        localPath: 'public/'
        remotePath: '/home/xaviergo/www'